import type { Metadata } from "next";
import { publicSans } from "./fonts/fonts";
import "./globals.css";

export const metadata: Metadata = {
    title: "Personal finance dashboard",
    description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.className}} bg-[hsl(var(--beige-100))] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
